# Info about you
name: Matěj Frič
position: Data Scientist & Student
email: matej.fric.mf@gmail.com
company_name: Stora Enso & VSB-TUO
company_url: https://www.storaenso.com
place_name: Ostrava, Czechia

# Blog info
title: Matěj Frič
description:
url: https://https://matejfric.github.io/
main_github_io: true
long_description: >-
    Welcome to my blog! I'm a Computer Science Master's student at VSB-TUO
    and a part-time Data Scientist at Stora Enso, where I bridge theoretical
    learning with practical applications. Join me on this journey as I explore
    the intersection of academia and real-world challenges.

# Social links
github_url: https://github.com/matejfric
linkedin_url: https://www.linkedin.com/in/matej-fric/
social:
  links:
    - https://www.linkedin.com/in/matej-fric/
    - https://github.com/matejfric/

# Images + files
logo: assets/img/photo.png
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
